### ISSUE TITLE
Le fichier client.py ne se lance pas

### ISSUE THREAD

**Issue by tcunique** [cbouilla/uglix4-public#1]
Bonjour,

Je lance le fichier avec la commande suivante, sous Ubuntu 22.04 : 
python3 client.py
ou
python client.py

Cependant rien ne se lance. La commande s'exécute et se termine tout de suite après.

Je reste à votre disposition pour toutes informations complémentaires.

Cordialement,

Thomas

**Comment by cbouilla** [comment]
Y a-t-il un message d'erreur affiché ?

**Comment by tcunique** [comment]
Non, la commande se lance et rien ne s'affiche.
